version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "votre-username"
    assignees:
      - "votre-username"
    commit-message:
      prefix: "pip"
      prefix-development: "pip-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    ignore:
      # Ignore major version updates for these packages
      - dependency-name: "flask"
        update-types: ["version-update:semver-major"]
      - dependency-name: "werkzeug"
        update-types: ["version-update:semver-major"]

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "votre-username"
    assignees:
      - "votre-username"
    commit-message:
      prefix: "docker"
      prefix-development: "docker-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "votre-username"
    assignees:
      - "votre-username"
    commit-message:
      prefix: "github-actions"
      prefix-development: "github-actions-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Enable version updates for npm (if applicable)
  - package-ecosystem: "npm"
    directory: "/web/static"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "votre-username"
    assignees:
      - "votre-username"
    commit-message:
      prefix: "npm"
      prefix-development: "npm-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    ignore:
      # Ignore major version updates for these packages
      - dependency-name: "jquery"
        update-types: ["version-update:semver-major"] 