labels:
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"
  - name: "priority: high"
    color: "ff0000"
    description: "High priority issue"
  - name: "priority: medium"
    color: "ffa500"
    description: "Medium priority issue"
  - name: "priority: low"
    color: "00ff00"
    description: "Low priority issue"
  - name: "security"
    color: "ff0000"
    description: "Security related issue"
  - name: "docker"
    color: "2496ed"
    description: "Docker related changes"
  - name: "python"
    color: "3776ab"
    description: "Python related changes"
  - name: "frontend"
    color: "f7df1e"
    description: "Frontend related changes"
  - name: "backend"
    color: "000000"
    description: "Backend related changes"
  - name: "testing"
    color: "00ff00"
    description: "Testing related changes"
  - name: "performance"
    color: "ff6b6b"
    description: "Performance related changes"
  - name: "ui/ux"
    color: "ff69b4"
    description: "User interface or experience changes"
  - name: "breaking change"
    color: "ff0000"
    description: "Breaking change"
  - name: "dependencies"
    color: "0366d6"
    description: "Dependency updates"
  - name: "needs-triage"
    color: "ffa500"
    description: "Needs to be triaged"
  - name: "wontfix"
    color: "ffffff"
    description: "This will not be worked on"
  - name: "duplicate"
    color: "cfd3d7"
    description: "This issue or pull request already exists"
  - name: "invalid"
    color: "e4e669"
    description: "Something is wrong"
  - name: "question"
    color: "d876e3"
    description: "Further information is requested"
  - name: "ready for review"
    color: "00ff00"
    description: "Ready for code review"
  - name: "work in progress"
    color: "ffa500"
    description: "Work in progress"
  - name: "blocked"
    color: "ff0000"
    description: "Blocked by another issue"
  - name: "approved"
    color: "00ff00"
    description: "Approved for merge"
  - name: "needs testing"
    color: "ffa500"
    description: "Needs testing"
  - name: "deployment"
    color: "0366d6"
    description: "Deployment related"
  - name: "monitoring"
    color: "00ff00"
    description: "Monitoring related"
  - name: "logging"
    color: "ffa500"
    description: "Logging related"
  - name: "api"
    color: "3776ab"
    description: "API related changes"
  - name: "database"
    color: "ff6b6b"
    description: "Database related changes"
  - name: "authentication"
    color: "ff0000"
    description: "Authentication related"
  - name: "authorization"
    color: "ff6b6b"
    description: "Authorization related"
  - name: "cryptography"
    color: "ff0000"
    description: "Cryptography related"
  - name: "malware-analysis"
    color: "ff0000"
    description: "Malware analysis related"
  - name: "network-analysis"
    color: "0366d6"
    description: "Network analysis related"
  - name: "web-security"
    color: "ff0000"
    description: "Web security related"
  - name: "reports"
    color: "00ff00"
    description: "Report generation related"
  - name: "projects"
    color: "ffa500"
    description: "Project management related" 